/// Flutter icons FlutterIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcon
///      fonts:
///       - asset: fonts/FlutterIcon.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData event_seat =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_full =
      IconData(0xf2c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_three_quarters =
      IconData(0xf2c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_half =
      IconData(0xf2c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_quarter =
      IconData(0xf2ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_empty =
      IconData(0xf2cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
